sudo: false

language: ruby

rvm:
  - 2.6.4

bundler_args: --without system_tests --jobs=3 --retry=3

before_install:
  - gem install bundler

script: bin/travis

matrix:
  fast_finish: true

env:
  matrix:
    - BUILD_TYPE=rspec
    - BUILD_TYPE=rubocop
